### ISSUE TITLE
[doc] dead link

### ISSUE THREAD

**Issue by jibe-b** [SwissDataScienceCenter/renga#115]
In page https://renga.readthedocs.io/en/latest/developer/code_repo_structure.html

the link https://github.com/SwissDataScienceCenter/renga-tutorials is dead.

**Comment by 3C111** [comment]
Hi Jibe-b, thanks for your comment. The repo that is linked there is in fact private, that is why the link seems dead. We will update the docs.

**Comment by jibe-b** [comment]
ok.
