### ISSUE TITLE
Define and use volumes

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renga#129]
https://github.com/SwissDataScienceCenter/renga/blob/28e40ab6b91e2b2ccda7f8d888dc8c6fa36ac0a0/docker-compose.yml#L127-L130

Issue: files generated by services are note wiped after `make wipe`.
Cause: the files are put in `./services` and never removed (also, they can only be removed by `root` on linux, c.f. user trick in https://github.com/SwissDataScienceCenter/renga-storage/blob/master/docker-entrypoint.sh).
Solution: do not bind mount `rw` volumes except the docker socket. Instead, declare and use volumes in the compose file.

**Comment by rokroskar** [comment]
yes, this was a mistake carried over from the incubator repo -- I thought we fixed it but maybe it was in a branch that was never merged. What's wrong with just removing the `services/gitlab` directory in `make wipe`? (right now it's removing `./gitlab` which doesn't exist)

**Comment by leafty** [comment]
The files are owned by `root` on linux. The behavior of `osxfs` storage driver is not the usual one (ownership not mapped).

**Comment by rokroskar** [comment]
👍 got it. Volumes it is.

**Comment by rokroskar** [comment]
we should do the same for `gitlab-runner`, btw

**Comment by rokroskar** [comment]
closed by #132
