### ISSUE TITLE
keycloak should run on port 80 in the container

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renga#134]
Exposing ports 80 and 443 as the default http/https ports avoids problems with token issuer

**Comment by rokroskar** [comment]
@leafty we'd like to be able to run keycloak on port 80 in the container so we don't have to do a redirect from 80 to 8080 outside the container -- see the `docker-compose` in #133. When I try to set the port using the `jboss.http.port` option, everything breaks -- could you please have a look?

**Comment by leafty** [comment]
Is this still an issue?

**Comment by rokroskar** [comment]
can close for now
