### ISSUE TITLE
include jupyterhub in helm charts

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renga#152]
add and configure jupyterhub in the helm charts (see e.g. https://github.com/jupyterhub/binderhub/tree/master/helm-chart) using our spawner. This is a continuation of #147 

---

addresses #146

**Comment by leafty** [comment]
TODOs before this one:
- [ ] waiting for #148 
- [ ] implement `RengaSpawner` that extends `KubeSpawner`

**Comment by rokroskar** [comment]
@leafty could you please add jupyterhub as a dependency to the renga chart and configure it so that it coexists with the other services? Then we can try out the `RengaKubeSpawner` that was created as a part of #148

**Comment by rokroskar** [comment]
closed via #161
