### ISSUE TITLE
Naming conventions for environmental variables

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renga#31]
## Proposal

- service related: `RENGA_{SERVICE}_{WHATEVER_WITH_UNDERSCORES}`
- global config for multiple services `RENGA_SERVICES_{...}`

## Acceptance

- [ ] `authorization`
- [x] `deployer`
- [ ] `graph`
- [ ] `storage`
- [ ] ...

--
cc @erbou @leafty @rokroskar @ebiiii

**Comment by rokroskar** [comment]
lets revisit this in a cleanup of development branches
