### ISSUE TITLE
Documentation: RENGA or Renga?

### ISSUE THREAD

**Issue by erbou** [SwissDataScienceCenter/renga#68]
Decide of the proper / consistent spelling for Renga/RENGA and apply everywhere in the docs.

**Comment by rokroskar** [comment]
Should be Renga, no? It's not an acronym

**Comment by leafty** [comment]
Agree on not an acronym. Using "RENGA" should only be accepted in titles, when all words are capitalized (e.g. README of this repo).

**Comment by erbou** [comment]
This is what we finally agreed on:
- Marketing materials: RENGA
- Documentation and code in github & readthedocs:
    - RENGA in logo and titles
    - Renga otherwise.

**Comment by rokroskar** [comment]
👍
